# *** hardware setup/configuration ***
run_number :  # Base run number, will be automatically increased; if none is given, generate filename
output_folder :  # Output folder for the telescope data; if none is given, the current working directory is used
m26_configuration_file :  # Configuration file for Mimosa26 sensors, default: 'm26_config/m26_threshold_8.yaml'
m26_jtag_configuration : True  # Send Mimosa26 configuration via JTAG, default: True
no_data_timeout : 30  # No data timeout after which the scan will be aborted, in seconds; if 0, the timeout is disabled
scan_timeout : 0  # Timeout after which the scan will be stopped, in seconds; if 0, the timeout is disabled; use Ctrl-C to stop run
max_triggers : 0  # Maximum number of triggers; if 0, there is no limit on the number of triggers; use Ctrl-C to stop run
send_data : 'tcp://127.0.0.1:8500'  # TCP address to which the telescope data is send; to allow incoming connections on all interfaces use 0.0.0.0
enabled_m26_channels : # Enabled RX channels, eg. ["M26_RX1", "M26_RX2", "M26_RX6"]; default None (=all planes)
#output_folder: telescope_data  # Name of the subfolder which will be created in order to store the telescope data
#filename: run_1  # Filename of the telescope data file

# *** trigger configuration ***
TLU :
    TRIGGER_MODE                         : 3  # Selecting trigger mode: Use trigger inputs/trigger select (0), TLU no handshake (1), TLU simple handshake (2), TLU data handshake (3)
    TRIGGER_LOW_TIMEOUT                  : 0  # Maximum wait cycles for TLU trigger to become low
    TRIGGER_SELECT                       : 0  # Selecting trigger input
    TRIGGER_INVERT                       : 0  # Inverting trigger input
    TRIGGER_VETO_SELECT                  : 0  # Selecting trigger veto
    TRIGGER_HANDSHAKE_ACCEPT_WAIT_CYCLES : 3  # TLU trigger minimum length in TLU clock cycles
    DATA_FORMAT                          : 2  # Select trigger data format: only trigger number (0), only time stamp (1), combined, 15bit time stamp + 16bit trigger number (2)
    EN_TLU_VETO                          : 0  # Assert TLU veto when external veto is high
    TRIGGER_DATA_DELAY                   : 8  # Depends on the cable length and should be adjusted (run tune_tlu.py script)
    TRIGGER_THRESHOLD                    : 0  # Trigger minimum length; if 0, the threshold is disabled

# *** Mimosa26 receiver configuration ***
M26_RX1 :
    EN : 0  # will be enabled automatically
    TIMESTAMP_HEADER : 1  # enable for assigning hits to a particular frame
M26_RX2 :
    EN : 0
    TIMESTAMP_HEADER : 1
M26_RX3 :
    EN : 0
    TIMESTAMP_HEADER : 1
M26_RX4 :
    EN : 0
    TIMESTAMP_HEADER : 1
M26_RX5 :
    EN : 0
    TIMESTAMP_HEADER : 1
M26_RX6 :
    EN : 0
    TIMESTAMP_HEADER : 1

# *** Mimosa26 JTAG configuration ***
GPIO_JTAG :
    OUTPUT :
    - 1
    OUTPUT_EN :
    - 0
