[satellites]

[satellites.Pymosa]
run_number = "None"  # Base run number, will be automatically increased; if none is given, generate filename
output_folder = "None"  # Output folder for the telescope data; if none is given, the current working directory is used
m26_configuration_file = "None"  # Configuration file for Mimosa26 sensors, default: 'm26_config/m26_threshold_8.yaml'
m26_jtag_configuration = true  # Send Mimosa26 configuration via JTAG, default: True
no_data_timeout = 30  # No data timeout after which the scan will be aborted, in seconds; if 0, the timeout is disabled
scan_timeout = 0  # Timeout after which the scan will be stopped, in seconds; if 0, the timeout is disabled; use Ctrl-C to stop run
max_triggers = 0  # Maximum number of triggers; if 0, there is no limit on the number of triggers; use Ctrl-C to stop run
send_data = 'tcp://127.0.0.1:8500'  # TCP address to which the telescope data is send; to allow incoming connections on all interfaces use 0.0.0.0
enabled_m26_channels = "None" # Enabled RX channels, eg. ["M26_RX1", "M26_RX2", "M26_RX6"]; default None (=all planes)