name: Software tests

on: push

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
    # Check out repo
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
            
    - name: Install pymosa
      run: |
        pip install --upgrade pip
        pip install -e .
        plugin_online_monitor pymosa/online_monitor

    - name: Headless display setup
      uses: pyvista/setup-headless-display-action@v3
      with:
        qt: true
    
    - name: Test
      run: pytest -s -v